GET http://localhost:3003/api/blogs


###
POST http://localhost:3003/api/blogs
Content-Type:application/json

{
    "title": "blogTitle",
  "author": "blogAuthor",
  "url": "blogURL",
  "likes": 666
}


###

POST http://localhost:3003/api/blogs
Content-Type:application/json

{
    "title": "blogTitle2",
  "author": "blogAuthor2",
  "url": "blogURL2",
  "likes": 777
}

###

POST http://localhost:3003/api/blogs
Content-Type:application/json

{
    "title": "blogTitle3",
  "author": "blogAuthor3",
  "url": "blogURL3",
  "likes": 888
}

###
POST http://localhost:3003/api/blogs
Content-Type:application/json

{
    "title": "blogTitle4",
    "author": "blogAuthor4",
    "url": "blogURL4",
    "likes": 999,
    "userId":"60a4a213450623ae751b7dcb"
}

###


POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MGE0YTIxMzQ1MDYyM2FlNzUxYjdkY2IiLCJpYXQiOjE2MjcwMjI2MzYsImV4cCI6MTYyNzAzMzQzNn0.TgT_fpuDpliigRujLPCziJ4xgV24IHWdU-oRsq2DJLQ

{
  "title":"test0725",
  "author":"0725",
  "url":"0725",
  "likes":725
}

###delete a blog###

DELETE http://localhost:3003/api/blogs/60fa7ec1dcf33fb495398ef1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MGE0YTIxMzQ1MDYyM2FlNzUxYjdkY2IiLCJpYXQiOjE2MjcwMjI2MzYsImV4cCI6MTYyNzAzMzQzNn0.TgT_fpuDpliigRujLPCziJ4xgV24IHWdU-oRsq2DJLQ


###delete with a wrong auth.
DELETE http://localhost:3003/api/blogs/60fa7ec1dcf33fb495398ef1
Authorization: bearer 44JhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MGE0YTIxMzQ1MDYyM2FlNzUxYjdkY2IiLCJpYXQiOjE2MjcwMjI2MzYsImV4cCI6MTYyNzAzMzQzNn0.TgT_fpuDpliigRujLPCziJ4xgV24IHWdU-oRsq2DJLQ